### ISSUE TITLE
How to use themes with the new Code node

### ISSUE THREAD

**Issue by niosus** [motion-canvas/motion-canvas#1040]
While a new `Code` node is fantastic I was wondering if it is possible to use some pre-defined code highlight theme from the ones available in the typical text editors, e.g. Monokai. As of now, there is a default theme coming from `LezerHighlighter` and I was not able to find any other pre-defined themes. While it is possible to set up custom themes, it would be nice to have some available by default. Am I just missing some setting?

**Comment by brend32** [comment]
If you want you can install Shiki code highlighter. It supports a lot of languages and has many themes.

https://github.com/brend32/motion-canvas/commit/942735aecf9108f10b328699deec8e1f7005bbce

**Comment by aarthificial** [comment]
@brend32 Instead of forking the repo you should consider releasing the highlighter as a standalone npm package.
This would let people easily install it in existing projects and would open the door to upstreaming it here in the future.

**Comment by niosus** [comment]
As a non-expert in this, I would prefer a way to enable themes in the framework and while the way suggested by @brend32 is helpful, it feels like there might still be a way to enable themes out of the box in Motion Canvas directly, what is your take on this @aarthificial?

**Comment by brend32** [comment]
> @brend32 Instead of forking the repo you should consider releasing the highlighter as a standalone npm package. This would let people easily install it in existing projects and would open the door to upstreaming it here in the future.

Highlihter (https://github.com/shikijs/shiki) is a standalone npm package. Only a adapter were created in the forked version.

**Comment by aarthificial** [comment]
I don't know what you mean by
> enable themes out of the box in Motion Canvas directly

Motion Canvas ships with only one default theme. The `LezerHighlighter` accepts a custom `HighlightStyle` so that people can use any CodeMirror theme they want.

For example, here's a CodeMirror theme for Monokai:
https://www.npmjs.com/package/@uiw/codemirror-theme-monokai

You can install it in your project:
```sh
npm i @uiw/codemirror-theme-monokai
```

And then use it when defining your LezerHighlighter:
```ts
import {parser} from '@lezer/javascript';
import {monokai} from '@uiw/codemirror-theme-monokai';

const Highlighter = new LezerHighlighter(parser, (monokai as any)[1][2].value);
```

We could provide a helper function to make the `(monokai as any)[1][2].value` construction less awkward. 
But other than that, I don't really see the reason for bundling every single theme that people may want with Motion Canvas given that the CodeMirror ecosystem has plenty of them already.

**Comment by niosus** [comment]
This looks great! That is exactly the reason why I added the documentation label to this issue at first, could we maybe add this to the docs for the noobs in type script like myself? I feel this tiny tutorial belongs in the docs of Motion Canvas to make it an even more complete package. Thoughts?

**Comment by philldev** [comment]
> I'm not sure what you mean by
> 
> > enable themes out of the box in Motion Canvas directly
> 
> Motion Canvas ships with only one default theme. The `LezerHighlighter` accepts a custom `HighlightStyle` so that people can use any CodeMirror theme they want.
> 
> For example, here's a CodeMirror theme for Monokai: https://www.npmjs.com/package/@uiw/codemirror-theme-monokai
> 
> You can install it in your project:
> 
> ```shell
> npm i @uiw/codemirror-theme-monokai
> ```
> 
> And then use it when defining your LezerHighlighter:
> 
> ```ts
> import {parser} from '@lezer/javascript';
> import {monokai} from '@uiw/codemirror-theme-monokai';
> 
> const Highlighter = new LezerHighlighter(parser, (monokai as any)[1][2].value);
> ```
> 
> We could provide a helper function to make the `(monokai as any)[1][2].value` construction less awkward. But other than that, I don't really see the reason for bundling every single theme that people may need with Motion Canvas given that the CodeMirror ecosystem has plenty of them already.

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/2b255161-e05c-413d-93ff-2b1a982f7ac1">

I got this error when using tokyo night theme. any idea why? thankyou

**Comment by aarthificial** [comment]
@philldev I can't reproduce the problem unfortunately.
I installed the theme:
```sh
npm i @uiw/codemirror-theme-tokyo-night
```
And the following code works just fine:
```tsx
import {parser} from '@lezer/javascript';
import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night';

import {Code, LezerHighlighter, makeScene2D} from '@motion-canvas/2d';
import {waitFor} from '@motion-canvas/core';
const Highlighter = new LezerHighlighter(
  parser,
  (tokyoNight as any)[1][2].value,
);

export default makeScene2D(function* (view) {
  view.add(<Code highlighter={Highlighter} code={'const a = 7;'} />);

  yield* waitFor(0.3);
});
```
![image](https://github.com/user-attachments/assets/1e889a3c-b491-457f-a79f-e4b6d36dab75)

Are you doing something differently?
If not, can you share the entire error message?

**Comment by philldev** [comment]
> @philldev I can't reproduce the problem unfortunately. I installed the theme:
> 
> ```shell
> npm i @uiw/codemirror-theme-tokyo-night
> ```
> 
> And the following code works just fine:
> 
> ```tsx
> import {parser} from '@lezer/javascript';
> import {tokyoNight} from '@uiw/codemirror-theme-tokyo-night';
> 
> import {Code, LezerHighlighter, makeScene2D} from '@motion-canvas/2d';
> import {waitFor} from '@motion-canvas/core';
> const Highlighter = new LezerHighlighter(
>   parser,
>   (tokyoNight as any)[1][2].value,
> );
> 
> export default makeScene2D(function* (view) {
>   view.add(<Code highlighter={Highlighter} code={'const a = 7;'} />);
> 
>   yield* waitFor(0.3);
> });
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/64662184/350693009-1e889a3c-b491-457f-a79f-e4b6d36dab75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Nzc4MDMsIm5iZiI6MTcyMTU3NzUwMywicGF0aCI6Ii82NDY2MjE4NC8zNTA2OTMwMDktMWU4ODlhM2MtYjQ5MS00NTdmLWE3OWYtZTRiNmQzNmRhYjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE1NTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMTAyNzdlYmNjYzQ1MmM3ZTZiOGY3Yjg5NjRjNWU1NWRjMTgxNDcxMWExOWY1NmU3MWQxOGNkMjc0YWE5NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bJRPhPJb9W7C1x1c0bRwqbUld2D2w_0fdCmQEQqENCY)
> 
> Are you doing something differently? If not, can you share the entire error message?

I'm sorry for not providing extra context, here is my code.
```ts
import { Code, LezerHighlighter } from "@motion-canvas/2d";
import { parser } from "@lezer/javascript";
import { tokyoNight } from "@uiw/codemirror-theme-tokyo-night";

Code.defaultHighlighter = new LezerHighlighter(
  parser.configure({
    dialect: "jsx ts",
  }),
  (tokyoNight as any)[1][2].value,
);

export default makeProject({
  scenes: [cover, outlines, introduction],
});
```

the only differences is the runtime, I'm using Bun to initialize Vite motion canvas project, and I'm using Bun to install the theme package

**Comment by maxxnino** [comment]
> ```ts
> const Highlighter = new LezerHighlighter(parser, (monokai as any)[1][2].value);
> ```

I got the same error too

**Comment by marcel-goldschen-ohm** [comment]
Same error for me :(

Code fragment:
```javascript
import {parser} from '@lezer/python';
import {githubLight} from '@uiw/codemirror-theme-github';
Code.defaultHighlighter = new LezerHighlighter(parser, (githubLight as any)[1][2].value);
```

Error:
```
2:26:06 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@uiw/codemirror-theme-github/esm/index.js:1:21: ERROR: Could not resolve "@babel/runtime/helpers/extends"
    at failureErrorWithLog (.../node_modules/esbuild/lib/main.js:1649:15)
    at .../node_modules/esbuild/lib/main.js:1058:25
    at .../node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Importing the parser and githubLight works fine. The parser works fine on its own. The error occurs only when I add the `(githubLight as any)[1][2].value` to the LezerHighlighter.

**Comment by cjosue15** [comment]
Hey, i found a solution, just install `"@babel/runtime"` in your dependencies :). i know this is not the best but for now works.

**Comment by marcel-goldschen-ohm** [comment]
Any ideas on how to control the color of colon ':' characters? I've tried digging through CodeMirror docs and tried setting all sorts of style tags in the Highlighter fed into the LezerHighlighter, but can't seem to figure out how to affect ':' chars. Any advice would be much appreciated.
